spring.application.name=OIDC_AccessToken

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

spring.security.oauth2.client.registration.yandex.client-id=${YANDEX_CLIENT_ID}
spring.security.oauth2.client.registration.yandex.client-secret=${YANDEX_CLIENT_SECRET}
spring.security.oauth2.client.registration.yandex.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.yandex.redirect-uri=http://localhost:8080/login/oauth2/code/yandex
spring.security.oauth2.client.registration.yandex.scope=login:email,login:info

spring.security.oauth2.client.provider.yandex.authorization-uri=https://oauth.yandex.ru/authorize
spring.security.oauth2.client.provider.yandex.token-uri=https://oauth.yandex.ru/token
spring.security.oauth2.client.provider.yandex.user-info-uri=https://login.yandex.ru/info?format=json
spring.security.oauth2.client.provider.yandex.user-name-attribute=default_email

app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-expiration-ms=900000
app.jwt.refresh-token-expiration-ms=86400000

logging.file.name=logs/application.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=14
logging.level.root=${LOG_LEVEL:INFO}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false